// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6mADjgR1qabM_OxmOClaBpMPCKtWTWxE',
    appId: '1:754029726829:web:ee845840228336af1d4364',
    messagingSenderId: '754029726829',
    projectId: 'mylez-labari-app',
    authDomain: 'mylez-labari-app.firebaseapp.com',
    storageBucket: 'mylez-labari-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA57fjXcerCj6-ugOJHTsBL5id33_oZaZ0',
    appId: '1:754029726829:android:dcbe6cd3b5e076191d4364',
    messagingSenderId: '754029726829',
    projectId: 'mylez-labari-app',
    storageBucket: 'mylez-labari-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzEJFcCWvKAK44C2cYPBk9NRIBfwUdjaA',
    appId: '1:754029726829:ios:91708cb82a52c32a1d4364',
    messagingSenderId: '754029726829',
    projectId: 'mylez-labari-app',
    storageBucket: 'mylez-labari-app.appspot.com',
    iosClientId: '754029726829-bmvjm592tht35p0ohdjm58ldb42u4g6t.apps.googleusercontent.com',
    iosBundleId: 'com.example.labari',
  );
}
